id: A4A40E47E
title: 'The Bright Lamp of the Heart Essence (Nyingtik Saldrön): A Guru Yoga'
type: translation
pechas:
- I4446BB8E
- I75A99875
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:13:23.903282
  last_modified_at: 2023-01-04 12:13:23.903286
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I4446BB8E/49DE: B35F
  I75A99875/8384: B35F
